[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pip install flask && python webhook_receiver.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
