[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python supercat_automation/pain_signal_receiver.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
